export const enum UserActionTypes {
	LOGIN_USER = 'LOGIN_USER',
	LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
	LOGIN_USER_ERROR = 'LOGIN_USER_ERROR',
	SET_ROLE = 'SET_ROLE',

	REGISTER_USER = 'REGISTER_USER',
	REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
	REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
}
